MainWindow:
  Filter: !!python/unicode 'Lima'
  Geometry: !!python/object/apply:PySide.QtCore.QByteArray
  - !!binary |
    AdnQywABAAD////5////+AAABRcAAALEAAAAAwAAABgAAAUNAAACugAAAAAAAA==
  SelectedItem: !!python/unicode 'Adriana Lima'
  SelectedPage: 38
  splitImagesState: !!python/object/apply:PySide.QtCore.QByteArray
  - !!binary |
    AAAA/wAAAAAAAAACAAAB+AAAAlABAAAABgEAAAAB
