MainWindow:
  Filter: !!python/unicode 'Tay'
  Geometry: !!python/object/apply:PySide.QtCore.QByteArray
  - !!binary |
    AdnQywABAAD////5////+AAABRcAAALEAAAAAwAAABgAAAUNAAACugAAAAAAAA==
  SelectedItem: !!python/unicode 'Taylor Fuchs'
  SelectedPage: 1
  splitImagesState: !!python/object/apply:PySide.QtCore.QByteArray
  - !!binary |
    AAAA/wAAAAAAAAACAAACNwAAAhEBAAAABgEAAAAB
