MainWindow:
  Filter: !!python/unicode ''
  Geometry: !!python/object/apply:PySide.QtCore.QByteArray
  - !!binary |
    AdnQywABAAAAAAAgAAAADQAABLQAAALZAAAAKgAAAC0AAASqAAACzwAAAAAAAA==
  SelectedItem: !!python/unicode 'Kate Walsh'
  SelectedPage: 4
  splitImagesState: !!python/object/apply:PySide.QtCore.QByteArray
  - !!binary |
    AAAA/wAAAAAAAAACAAACEAAAAa4BAAAABgEAAAAB
